### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by eunseokOh** [vimeo/vimeo.py#103]
I have written the code below and an error occurs.
plz help me..

HTML

```
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
 <input type="file" name="file_data" />
 <input type="submit" value="ok" />
</form>
```

views.py (def post)
```
 v = vimeo.VimeoClient(
                token = token
   )


         
        h = v.post('/me/videos')
        headers = { 'content-Type': req.FILES['file_data'].content_type,
                    'Content-Length':str(req.FILES['file_data'].size)
        }


        v.upload(req.FILES['file_data'])
```

**Comment by bongster** [comment]
@eunseokOh  i also arise this issue. i spend a time for debug.

i found 504 error are arise at upload video file at ticket url.

the code is `_make_pass` function in `vimeo/upload.py` 

maybe `1512341765.cloud.vimeo.com` this server are not health.

**Comment by bongster** [comment]
and then when i run command `ping 1512341765.cloud.vimeo.com` that server are turn `Reqeust timeout`

**Comment by bongster** [comment]
did you know how to notice to vimeo developer team in github?

**Comment by bongster** [comment]
@Dashron Is this same issue i created, could you follow this issue?

**Comment by eunseokOh** [comment]
Unfortunately, I do not know... 'aaron@dashron.com' I will send an e - mail.
