### ISSUE TITLE
Replacing a video completes successfully but doesn't show correctly on the site

### ISSUE THREAD

**Issue by jawache** [vimeo/vimeo.py#109]
I've created a video to explain show you exactly what I'm seeing: https://vimeo.com/244261377

I've used the vimeo python api to replace a set of my videos, I've got all the perms and the API is working, no errors, and reports the replace completed successfully.

When checking the results I see something super weird:

1) Goto https://vimeo.com/197887144, this is the old video (you can tell since the start screen says Angular 2: From Theory To Practice at the bottom)
2) Click on the first video in the My Videos list, this video has the SAME URL: https://vimeo.com/197887144 but shows the new uploaded video (you can tell since the start screen says just angular.codecraft.tv at the bottom)

So my upload to replace the video is complete, I can see the replaces video on the site but only if I click on it.

Cheers,

Asim

```
for line in videos.split("\n"):
    file, id = line.split("	")
    print "Uploading", file, "to", id
    video_uri = v.replace(
        video_uri='/videos/' + id,
        filename='/Users/jawache/Dropbox/AngExports/' + file)
    print video_uri
    print " ------ Done ------"



Uploading 1.plunker.mp4 to 197887144
/videos/197887144
 ------ Done ------
```

**Comment by erunion** [comment]
That's really strange! Can you create a ZenDesk ticket with our support team? That'd be the best way to help you get this figured out.

https://vimeo.com/help/contact#tech-api

**Comment by erunion** [comment]
Hey @jawache, this turned out to be a bug in some new video versioning work that we did. A fix will be going live shortly.

**Comment by pointoflife14** [comment]
I have this same problem as well! Apparently "fixing it shortly" takes 4 years?!? Still no fix! I really don't want to use YouTube, but have no choice now! Geez

**Comment by erunion** [comment]
@pointoflife14 Sorry to hear that. I no longer work at Vimeo, but if you reach out to their support through the normal channels someone there should hopefully be able to help you out.
