### ISSUE TITLE
v.get('https://api.vimeo.com/me/videos').content is a str , should be a dict

### ISSUE THREAD

**Issue by Loewkie** [vimeo/vimeo.py#110]
v.get('https://api.vimeo.com/me/videos').content has the structure of a dictionary (which I want, so that I can select the data I need), but it has the data type str. Can you fix this?

**Comment by gabrielgisoldo** [comment]
There's no problem at all. To get it as dict you can use json in place of content likes this:
v.get('https://api.vimeo.com/me/videos').json()

**Comment by Loewkie** [comment]
If I do that all I get is:

<bound method Response.json of <Response [200]>>
Data type 'instancemethod'

**Comment by gabrielgisoldo** [comment]
You're welcome! Just close the issue later :)
