### ISSUE TITLE
no attribute vimeo client

### ISSUE THREAD

**Issue by ire4ever1190** [vimeo/vimeo.py#112]
when ever I try to use the code listed in the readme to auth I get this error

AttributeError: module 'vimeo' has no attribute 'VimeoClient'

any ideas?

**Comment by erunion** [comment]
I haven't seen that one before. Can you paste the full code you're running? What version of PyVimeo do you have installed?

**Comment by ire4ever1190** [comment]
heres the fill code
 `
import vimeo 
import glob

#AUTH
v = vimeo.VimeoClient(
    token=YOUR_ACCESS_TOKEN,
    key=YOUR_CLIENT_ID,
    secret=YOUR_CLIENT_SECRET)


for filename in glob.glob('*.mp4'):
	print(filename)
`
Im using PyVimeo-0.4.1 with python2
I have also tried using python3

**Comment by erunion** [comment]
Strange, that code works for me on a fresh machine and PyVimeo-0.4.1 install.

```
$ pip list | grep -i pyvimeo
PyVimeo (0.4.1)
$ python test.py 
Untitled.mp4
VID_20171118_163815.mp4
VID_20171203_091848.mp4
VID_264410812_104045_324.mp4
$ cat test.py 
import vimeo
import glob

v = vimeo.VimeoClient(
    token='',
    key='',
    secret='')

for filename in glob.glob('*.mp4'):
    print(filename)
$ python --version
Python 2.7.10
```

Can you try deleting and re-installing PyVimeo? Maybe the package got corrupted during installation.

**Comment by ire4ever1190** [comment]
I found the issue. I was naming the file 'vimeo.py' and so it tried to load that instead of the library. Sorry for this
