### ISSUE TITLE
maximum upload specified(1818091 bytes) has been reached error

### ISSUE THREAD

**Issue by QurQuma** [vimeo/vimeo.py#115]
When uploading a new file to vimeo

`video_uri = v.upload(folder_path + board_type + str(n) + '.mp4', data={'name': hub_title + data['name'], 'description': data['notes']})`

I always get the following error:

1818091 bytes uploaded ...
maximum upload specified(1818091 bytes) has been reached

What's going wrong?
Thanks,
Francesco

**Comment by erunion** [comment]
What you're seeing is just debug from the upload process. If you print out `video_uri`, you should have a URI from your uploaded video.

Example from our `/example/upload.py`:

```python
Uploading: /Users/erunion/Desktop/VID_264410812_104045_324.mp4
672111 bytes uploaded ...
maximum upload specified(672111 bytes) has been reached
"/Users/erunion/Desktop/VID_264410812_104045_324.mp4" has been uploaded to https://vimeo.com/255841076
The title and description for /videos/255841076 has been edited.
The transcode status for /videos/255841076 is: in_progress
```
