### ISSUE TITLE
"upload_quota" returns empty 

### ISSUE THREAD

**Issue by eakbas** [vimeo/vimeo.py#116]
This call returns an empty json, is it normal? 

`about_me = v.get('/me', params={ 'fields': 'upload_quota' })` 

I am using the latest version of  PyVimeo 1.0.0.

**Comment by tommypenner** [comment]
@eakbas To troubleshoot, we need to look at the token used to authenticate that request. Please email Vimeo using the contact form linked below, and provide a link back to this GitHub issue. Thanks!

https://vimeo.com/help/contact
