### ISSUE TITLE
'TusUploadFailed' object has no attribute 'text'

### ISSUE THREAD

**Issue by amrutadotorg** [vimeo/vimeo.py#122]
Hi, I'm getting
232783872 bytes uploaded ...
'TusUploadFailed' object has no attribute 'text'

I can upload smaller files 60M but not a big ones 5G

the module version looks good, 

pip show tuspy
Name: tuspy
Version: 0.2.1

**Comment by Onebrownsound** [comment]
@amrutadotorg 👋 The latest build should fix this issue, please reach out if it does not.

**Comment by amrutadotorg** [comment]
Hi, now I'm getting 
335544320 bytes uploaded ...
Communication with tus sever failed with status 502

Is it possible to retry the connection with the tus server?

**Comment by amrutadotorg** [comment]
Yes I can. The error appears after a couple of minutes.

curl -I https://files.tus.vimeo.com/HTTP/1.1 200 OK
Date: Thu, 28 Jun 2018 17:55:52 GMT
Content-Length: 222
Content-Type: text/plain; charset=utf-8
Via: 1.1 google
Alt-Svc: clear

**Comment by erunion** [comment]
Ok, good to know. We'll try and get some retry logic in by the end of the week.

**Comment by amrutadotorg** [comment]
thank you, please let me know once it is ready

**Comment by erunion** [comment]
@amrutadotorg We've pushed some retry logic into v1.0.4.
