### ISSUE TITLE
Attemp to retrieve offset fails with status 502

### ISSUE THREAD

**Issue by amrutadotorg** [vimeo/vimeo.py#128]
Hi, I'm trying to upload 6.7G file, after uploaded 500M+ chunk I'm getting:

522462080 bytes uploaded ...
Attemp to retrieve offset fails with status 502

moreover partially uploaded video can be seen at https://vimeo.com/280318432

I have 1.0.5 version

Thank you

**Comment by erunion** [comment]
Talked with our upload team today, and they found some issues in our backend that they're currently working on fixing. I'll let you know when those fixes are complete.

**Comment by tagiles** [comment]
I'm getting the same error status code, same situation, different message - may be related?

3.5gb file, after 1g fails with 502:

  File "C:\Python27\ArcGIS10.6\lib\site-packages\vimeo\upload.py", line 147, in __perform_tus_upload
    'Unexpected error when uploading through tus.'
VideoUploadFailure: Communication with tus sever failed with status 502

**Comment by erunion** [comment]
@tagiles Definitely related. Talked with our upload team and they tell me that their fix is ~80% complete, but there's some changes we can put into the SDK to alleviate it a bit. We'll try to get to those fixes this week.

I'll update this thread when that's complete, and apologies for the troubles.

**Comment by mgiles86** [comment]
@erunion Any idea when this fix will be released? thx

**Comment by erunion** [comment]
@mgiles86 We have an open pull request https://github.com/vimeo/vimeo.py/pull/130, it just needs some review. Should be able to tag a new release tomorrow.

**Comment by erunion** [comment]
@mgiles86 @amrutadotorg @tagiles This fix has been tagged to 1.0.6. Please let us know if you have any additional issues.

https://github.com/vimeo/vimeo.py/releases/tag/1.0.6

**Comment by geomatics-nwrc** [comment]
@erunion In 1.0.6 I am still having issues with large files. I have been able to upload a 1.2 gb file successfully, but that same file failed on a later run. Anything larger consistently fails and anything smaller consistently works.

One of the following errors are reported on a crash:
Server reported: (56, 'SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054')
Server reported: (55, 'SSL_write() returned SYSCALL, errno = 10053')
