### ISSUE TITLE
pyvimeo 1.0.6 has requirement tuspy==0.2.1

### ISSUE THREAD

**Issue by amrutadotorg** [vimeo/vimeo.py#131]
Hi, I'm getting

pyvimeo 1.0.6 has requirement tuspy==0.2.1, but you'll have tuspy 0.2.3 which is incompatible.

is it safe to upgrade tuspy?

thank you

**Comment by amrutadotorg** [comment]
it looks it is not safe, I'm getting
'exceptions.UnicodeDecodeError' object has no attribute 'status_code'

can you make pyvimeo compatibile with tuspy>0.2.1 ?

**Comment by erunion** [comment]
Sure, we'll update it to support that.

**Comment by erunion** [comment]
PyVimeo 1.0.7 now allows tuspy>=0.2.1. Let us know if you're still having trouble.

**Comment by erunion** [comment]
We've unfortunately had to downgrade tuspy back to 0.2.1 because 0.2.2 has some incompatible changes on Python 2.7.x.

See https://github.com/vimeo/vimeo.py/pull/136 for more details.
