### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by erunion** [vimeo/vimeo.py#140]
We've been getting a number of support cases over the past few months for upgrading tuspy to the latest version (https://github.com/vimeo/vimeo.py/pull/136). Unfortunately we can't do that because support for Python 2 was dropped in version 0.2.2.

Let's drop our support for Python 2 as well, upgrade tus, and release a 2.0 release. Let's also branch off the current master so we can retain the ability to do support releases for the 1.x release branch if need be.

**Comment by amrutadotorg** [comment]
Hi, any progress on 2.0 release?

thank you

**Comment by erunion** [comment]
Unfortunately no not so far. We've been very busy with other projects and haven't had very much time to devote to a new release. We're hoping to get something going next month.

**Comment by amrutadotorg** [comment]
ok thank you

**Comment by xtsimpouris** [comment]
Hi, is there any news on this? Thanks

**Comment by hugovk** [comment]
Please see PR https://github.com/vimeo/vimeo.py/pull/147 to drop support for Python 2.
