### ISSUE TITLE
Uploading gives tus error for files > 5mb.

### ISSUE THREAD

**Issue by brunoreisfm** [vimeo/vimeo.py#150]
In the issue #135 @edmenendez seemed to solve by changing the verions of tuspy. I did the same but here it's not working:

Versions:
![image](https://user-images.githubusercontent.com/35741326/64071473-2a8fdf80-cc51-11e9-8a1c-e99a4074afe1.png)

Error:
```
  File "vimeo_upload.py", line 47, in <module>
    video_id = client.upload(file_name, data={'name': file_name,})
  File "C:\Python27\lib\site-packages\vimeo\upload.py", line 78, in upload
    return self.__perform_tus_upload(filename, attempt, chunk_size=chunk_size)
  File "C:\Python27\lib\site-packages\vimeo\upload.py", line 161, in __perform_tus_upload
    'Unexpected error when uploading through tus.'
vimeo.exceptions.VideoUploadFailure: (55, 'SSL_write() returned SYSCALL, errno = 10053')
```

That file is only 50mb... For smaller files (<5mb) I'm not getting an error.

Can someone help?

Thanks!

_Originally posted by @brunoreisfm in https://github.com/vimeo/vimeo.py/issues/135#issuecomment-526885826_

**Comment by jaylinski** [comment]
Version 1.1.0 uses an updated `tuspy` package. It should fix your issue.

**Comment by fisherinnovation** [comment]
Please comment pending you are still encountering this issue. As mentioned this should be fixed in the latest version.
