### ISSUE TITLE
Create A Live Event Error 404

### ISSUE THREAD

**Issue by ColvrayC** [vimeo/vimeo.py#159]
Hello,

I am just starting the integration of vimeo on my web platform for lives (I have a premium account)

Currently, the client connects well with this code:

`vimeo.VimeoClient(token=settings.VIMEO_ACCESS_TOKEN,key=settings.VIMEO_CLIENT_ID,secret=settings.VIMEO_CLIENT_SECRET)`

Until then, no worries.

Then I do a test to create a live with the following code:

`uri = '/me/live_events'`
`response= client.post(uri, data={'title':'test from api'})`

And I have a 404 feedback, I also did the test directly from vimeo with message : 

![response](https://user-images.githubusercontent.com/14889813/83156439-b496a700-a102-11ea-9f0a-6524b6a11de9.JPG)

Note that the only two fields required are client_id and title.

And my scopes token : 

![scopes](https://user-images.githubusercontent.com/14889813/83156603-e60f7280-a102-11ea-94d4-133d19193614.JPG)

I don't see where my mistake may be

Thanks for your help ! :)

**Comment by jaylinski** [comment]
Have you tried the other two endpoints?

* https://api.vimeo.com/users/{user_id}/live_events
* https://api.vimeo.com/live_events
* https://api.vimeo.com/me/live_events

**Comment by avianheit07** [comment]
I've encountered the same issue, have you found the fix to this one yet? 
Even with the 'Try it out' in the API doesn't work.

**Comment by avianheit07** [comment]
@ColvrayC I think the issue we encountered is due to the plan of the account we are using. I used the premium account, and will be switching to enterprise.
