### ISSUE TITLE
Push version 1.1.0 to PyPI

### ISSUE THREAD

**Issue by jaylinski** [vimeo/vimeo.py#161]
Hi @muglug, sorry for pinging you again, but it would be nice if you could push the new version (1.1.0) to PyPI (https://pypi.org/project/PyVimeo/).

As requested in:
* https://github.com/vimeo/vimeo.py/pull/146#issuecomment-632354585
* https://github.com/vimeo/vimeo.py/pull/146#issuecomment-636715180

I think this would also resolve a lot of those new issues (#160, #156, #155).

**Comment by fisherinnovation** [comment]
@jaylinski Thanks for reporting. This should now be resolved - https://pypi.org/manage/project/PyVimeo/release/1.1.0/

Let me know if you are still encountering issues.
