### ISSUE TITLE
Video Subdomain embed not working

### ISSUE THREAD

**Issue by phanuelayuka** [vimeo/vimeo.py#165]
Allow me to cross post here since the Vimeo support take days to reply yet we are on the business plan.

We have a couple of subdomains e.g dn1.example.com, dn2.example.com and example.com as the main domain. In the video privacy settings we have added the allow embed to anywhere --- we changed to this after adding the subdomains to the video privacy settings and things were still not working. Videos can be viewed in allow subdomains except one - dn1.example.com. Is there a way to fix this?

This is happening a few days after we had issues with teams permissions which took a whole month to be resolved.

**Comment by jaylinski** [comment]
Has this anything to do with this python package?
