### ISSUE TITLE
Here's a package for additional API support

### ISSUE THREAD

**Issue by KalobTaulien** [vimeo/vimeo.py#176]
**Note:** This is not an issue. 

Since this repo seemed to be unmaintained for at least a couple years now, we (@Arbington) needed to write some API wrapper code to work with tens of thousands of videos. 

If you need additional API support in Python, come check out **[python-vimeo](https://github.com/arbington/python-vimeo)**. It includes _this_  package (PyVimeo) - it's just an additional layer of API support for Vimeos API in Python.

**Comment by aaronm67** [comment]
This library is officially supported by Vimeo.

**Comment by KalobTaulien** [comment]
Yes, it is, and it's missing about 99% of the API support provided by Vimeo. The docs and README even references Python 2. This repo needs to be updated but the last commit was.. 2 years ago?

**Comment by KalobTaulien** [comment]
Yes it is, and it's insanely outdated and lacking about 99% of the functionality that Vimeo's API supports. 

Thanks for editing my original comment too, that was a nice touch. Nothing like blocking other developers from simple api support. Looking forward to seeing this comment edited or removed entirely. 

> If you need additional API support in Python, come check out [python-vimeo](https://github.com/arbington/python-vimeo). It includes this package (PyVimeo) - it's just an additional layer of API support for Vimeos API in Python.

**Comment by aaronm67** [comment]
There are instructions on the developer site on having third-party libraries approved, this isn't the appropriate place to promote unreviewed libraries.
