### ISSUE TITLE
URGENT!!!.....How to create a folder inside folder ?

### ISSUE THREAD

**Issue by Rishav-hub** [vimeo/vimeo.py#177]
I am using the original Vimeo API but am not able to create a folder inside a folder.
image
![image](https://user-images.githubusercontent.com/57321948/151182323-1f0147a8-430c-4f35-833b-609e6fdf39a1.png)

The response is 405!!. Any help. Can you suggest how to do that?

**Comment by aaronm67** [comment]
You can use a "parent_folder_uri" parameter on /me/projects.

So

POST /me/projects' data = { parent_folder_uri = '/users/12345/projects/6789', 'name' = 'NLP', etc }

**Comment by Rishav-hub** [comment]
> You can use a "parent_folder_uri" parameter on /me/projects.
> 
> So
> 
> POST /me/projects' data = { parent_folder_uri = '/users/12345/projects/6789', 'name' = 'NLP', etc }

Thank Kyou @aaronm67 I just spent 2 hrs on this silly thing
