### ISSUE TITLE
"You have been banned" error when trying to post comment with token of another user.

### ISSUE THREAD

**Issue by Quohen-Leth** [vimeo/vimeo.py#181]
Hi! I'm trying to give users possibility to post a comments on Vimeo video using OAuth.
Here is my code:
```python
# Initializing client.
client = vimeo.VimeoClient(
    token=config["access_token"],
    key=config["client_id"],
    secret=config["client_secret"]
)
```

```python
# Making URI to get auth code.
scope_list = ["public", "private", "interact"]
auth_url = client.auth_url(scope_list, REDIRECT_URI, STATE)
```

```python
# Getting code from REDIRECT_URI params.
code = request.GET.get("code", None)
state = request.GET.get("state", None)
```

```python
# Getting access token.
access_token, _user, _scope = client.exchange_code(code, REDIRECT_URI)
```

```python
# Using this token to post a comment
comment = {"text": "Some comment"}
video_url = f"https://api.vimeo.com/videos/{video_id}/comments/"
response = client.post(
    video_url, headers={"Authorization": f"bearer {access_token}"}, data=comment}
)
```

Everithing goes well, except the last step.
When client with its `config["access_token"]`, registered previously for "my app", tries to post a comment with token of another user `access_token` it got "You have been banned" error.

How to use token of end user correctly?

**Comment by aaronm67** [comment]
The "You have been banned" message is incorrect here. 

The issue you're receiving is the token must have the "interact" scope to post comments.

**Comment by Quohen-Leth** [comment]
> The "You have been banned" message is incorrect here, thank you for letting us know.
> 
> The issue you're receiving is the token must have the "interact" scope to post comments.

Thank You. I didn't set scopes correctly.
