### ISSUE TITLE
NameError: name 'uri' is not defined

### ISSUE THREAD

**Issue by ruppen** [vimeo/vimeo.py#182]
Hy I installed the SDK with  "pip install PyVimeo" which didn't output any errors. 
But when I run following code I get a NameError: name 'uri' is not defined

```
import vimeo

client = vimeo.VimeoClient(
  token='xxxx',
  key='xxxxx',
  secret='xxxx
)
```

response = client.get(uri)
print(response.json())

Output:
Traceback (most recent call last):
  File "/home/user/Development/project/playlistmovervimeo.py", line 9, in <module>
    response = client.get(uri)
NameError: name 'uri' is not defined

Can anybody help me with that? I do not know where to start looking.
Kind regards

**Comment by hedyyytang** [comment]
Hi @ruppen , what is the URI you were trying to make the call for?

**Comment by ruppen** [comment]
I might just have figured it out.
URI is supposed to be replaced by https://api.vimeo.com/tutorial or something like that. Am I right?

That was not so clear by this guide here: https://developer.vimeo.com/api/guides/start
Sory I am still very new to PYTHON and APIs
Thanks
