### ISSUE TITLE
emojis, U+10000 (F0, F1, F2, F3) unicode support

### ISSUE THREAD

**Issue by drzraf** [vimeo/vimeo.py#185]
4 bytes unicode characters (like 📷) are garbled when saved as part of the video description

It seems like backend DB/encoding only supports up to 3 bytes UTF-8 characters. This is definitely a terrible limitation that must be fixed.

**Comment by aaronm67** [comment]
This isn't related to this library, it's a sitewide limitation. If you'd like to see a change, you can file a feature request at https://vimeo.com/help/contact
