### ISSUE TITLE
Python SyntaxError in `exceptions.py`

### ISSUE THREAD

**Issue by bluebinary** [vimeo/vimeo.py#188]
We just encountered a syntax error in the latest version of the Vimeo client on PyPi, version `1.1.1`, released today (05/11/2024):

The Python `SyntaxError` error is being caused by invalid syntax on line 24 of `exceptions.py` where the `elif` is terminated with two colons `::` instead of one:

```
.../site-packages/vimeo/upload.py:7: in <module>
    from . import exceptions
E     File "/usr/local/lib/python3.10/site-packages/vimeo/exceptions.py", line 24
E       elif hasattr(response, 'message')::
E                                         ^
E   SyntaxError: invalid syntax
```

https://github.com/vimeo/vimeo.py/blob/4475b6151b0e91ba88a64abc323cca78452bd3cb/vimeo/exceptions.py#L24

Thank you for making the Python Vimeo client library available and for any assistance you can offer in resolving this issue.

**Comment by Onebrownsound** [comment]
Fixed in https://pypi.org/manage/project/PyVimeo/release/1.1.2/ . Thanks for pointing this out!

**Comment by bluebinary** [comment]
Thank you for the quick response and the fix, we really appreciate it!
