### ISSUE TITLE
Setting title or permissions

### ISSUE THREAD

**Issue by emptygalaxy** [vimeo/vimeo.py#51]
Can anyone help me do more with this API than uploading a file?
It seems like I can only upload a file with this API and not even change the name of the video, as it gets uploaded as "Untitled".
If it's only that, this would render this API not very useful.

**Comment by greedo** [comment]
You can make GET, POST, PUT, PATCH, DELETE requests using our [api endpoints](https://developer.vimeo.com/api/endpoints) and some JSON data

Example: https://gist.github.com/greedo/4e92163a7a1a4f496cf6

**Comment by BenderCy** [comment]
I am doing a:

video_uri = v.upload('video.mpg')
v.patch(video_uri, data={'name':"myname"})

and I am getting a 403. I can't seem to get this to work at all and I've tried several different ways without success.
