### ISSUE TITLE
ReadTimeout while trying to upload captions.

### ISSUE THREAD

**Issue by samcarecho** [vimeo/vimeo.py#54]
While trying to upload captions, I keep getting ReadTimeout exceptions.
Can someone shade a light on how to solve this?

Here is my upload function:

    def upload_vimeo_track(uri, lang, track_file):
        v = vimeo.VimeoClient(
            token="removed",
            key="removed",
            secret="removed")

        track = "./caption_files/%s" % track_file

        while True:
            try:
                response = v.upload_texttrack(uri, 'captions', lang, track)
                return response
            except (ReadTimeout, ConnectTimeout) as e:
                print e
                time.sleep(30)
                pass

Here it is the connection log:

    INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.vimeo.com
    send: 'POST /videos/106328451/texttracks HTTP/1.1\r\nHost: api.vimeo.com\r\nContent-Length: 63\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/vnd.vimeo.*;version=3.2\r\nUser-Agent: pyvimeo 0.1; (http://developer.vimeo.com/api/docs)\r\nConnection: keep-alive\r\nContent-Type: application/json\r\nAuthorization: Bearer removed\r\n\r\n{"type": "captions", "name": "-B8Fqmkbl5I_0", "language": "en"}'
    reply: 'HTTP/1.1 201 Created\r\n'
    header: Date: Sun, 25 Jan 2015 10:34:46 GMT
    header: Server: Apache
    header: Vary: Accept,Vimeo-Client-Id,Accept-Encoding
    header: Cache-Control: no-cache, max-age=315360000
    header: Location: /texttracks/2176007
    header: Expires: Wed, 22 Jan 2025 10:34:46 GMT
    header: Content-Encoding: gzip
    header: Content-Length: 263
    header: Keep-Alive: timeout=100, max=100
    header: Connection: Keep-Alive
    header: Content-Type: application/vnd.vimeo.video.texttrack+json
    header: Via: 1.1 dca1-10
    DEBUG:requests.packages.urllib3.connectionpool:"POST /videos/106328451/texttracks HTTP/1.1" 201 263
    INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): captions.cloud.vimeo.com
    send: 'PUT /captions/2176007?expires=1422182586&sig=removedHTTP/1.1\r\nHost: captions.cloud.vimeo.com\r\nContent-Length: 6119\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/vnd.vimeo.*;version=3.2\r\nUser-Agent: pyvimeo 0.1; (http://developer.vimeo.com/api/docs)\r\nConnection: keep-alive\r\nAuthorization: Bearer removed\r\n\r\n'
    send: <open file './caption_files/-B8Fqmkbl5I_0', mode 'r' at 0x0293B968>
    sendIng a read()able
    HTTPSConnectionPool(host='captions.cloud.vimeo.com', port=443): Read timed out. (read timeout=30)

One more information. Despite the timeout, most likely caused by an error on the Vimeo server, ~~the caption is uploaded to it's related video~~.

I just checked and in reality the caption information is shown at the "Advanced" tab, but no caption file is linked to it, therefore the file upload is not successful. 
Just the first step of the captions upload process is successful, the second step, the file upload itself, is not.

**Comment by greedo** [comment]
@samcarecho this error is coming from `urllib3` and as you noticed we are not re-catching and wrapping the error in our own library.

If you contact us directly through [vimeo.com/help/contact](vimeo.com/help/contact) and share your exact request with [runscope](https://www.runscope.com/docs/sharing) I may be able to help you further.

**Comment by samcarecho** [comment]
Sorry @greedo I will not sign-up of a paid third party service, even though it offers a 30 day free trial and spend time going through it's documentation just for your convenience. I'm really busy. I would ratter just share the requests logs in a plain txt file. 

If I can't get help or you can't help me I will be forced to strongly advise the non-profit to which I'm working as a volunteer to avoid Vimeo. I will make my case showing to them all the 500 errors the Vimeo servers are returning, some of which are returned as "unknown error".

I opened the issue hopping for a mutual effort, where both of us would work together to reach the non-profit goal and identify possible errors within the Vimeo API. I even sent a message to the e-mail you have shared publicly on your GitHub account. To which so far I received no reply.

Regarding the captions upload, I can't wait and I have already solved the problem using server-side JavaScript and cron jobs. I have set uploads to sleep for 15 seconds after each server error and then retry, and to sleep for 10 seconds after a successful upload. This is working and mitigating server errors , but it is taking a painful long time.

The captions uploads is an emergency and just tip of the iceberg.
I'm planing and implementing for the non-profit, as a volunteer, a captions translation management system that will make use of both YouTube and Vimeo APIs, for publishing purpose.

**Comment by Dashron** [comment]
The pricing plans on runscope.com are new. We were not aware of the change.

We tend to send users through runscope because it provides 2 powerful features.
1. It's an http proxy (like wireshark or charles), so we get the exact values your code sends and receives instead of example code which may work different from system to system.
2. The requests are sharable, editable and repeatable.

The vast majority of developers we interact with do not have the understanding or ability to use charles or wireshark to identify their http logs, so runscope was our go-to solution. If you are comfortable with other http proxies we are more than happy to receive text documents containing your entire request and response cycle.

Additionally @greedo asked to move to email because we should test the exact access token you are using, and verify that there are no conflicts there. We do not want your access token exposed to the world. 

If you would like to continue conversation here we are more than happy, just verify with @greedo via email, or some private contact which access token you are using along with the previously mentioned request logs.

**Comment by Dashron** [comment]
After some more review, Runscope is still 100% free for a single user, making up to 10k requests per month. You can find that on their pricing and plans page: https://www.runscope.com/pricing-and-plans.

It's definitely confusing, but they are by far the best http proxy I have ever used. I recommend you give them a shot, but again we are more than happy  to receive text logs from some other tool.

**Comment by samcarecho** [comment]
Thanks Aaron for your attention.


When a visited the Runscope website, the only option available were the 30
day free trial, a per this link:
https://www.runscope.com/signup

Please. don't take me wrong, Runscope seems to be an amazing service, I
just do not have, right now, the time to go through it's documentation.
As soon as I get some free time I will take a deep look on their
documentation, as their service seems to be something that will probably
easy my life.
For now, I will dump the HTTP communication using Wireshark and send it to
either you or @greedo.

What e-mail address should I send the dump to?
I just have the public @greedo address, which is not a @vimeo.com address.


Cheers,
Sam

**Comment by greedo** [comment]
@samcarecho you can send it to me - joec@vimeo.com

I'll look into it.

**Comment by samcarecho** [comment]
Thank you @greedo, I will send you the dump.

**Comment by greedo** [comment]
@samcarecho we made some changes on our captions backend that should solve this problem. It might be best to build in some retry logic by catching that `urllib3` error.

Feel free to reopen this issue again if you have problems again.

**Comment by samcarecho** [comment]
@greedo I will test it again  as soon as possible. 
Thanks
