### ISSUE TITLE
authorization code grant request does not set "state"

### ISSUE THREAD

**Issue by justinruggles** [vimeo/vimeo.py#55]
The API documentation at https://developer.vimeo.com/api/authentication#generate-redirect says that the "state" param is required and should be validated by the client, but I don't see where the Python library is setting it or validating it.

**Comment by justinruggles** [comment]
Sorry, I suppose validation would be left up to the user, but I don't see the option to set it.

**Comment by greedo** [comment]
@justinruggles You could set it [here](https://github.com/vimeo/vimeo.py/blob/master/vimeo/auth/authorization_code.py#L28)

**Comment by Dashron** [comment]
We should add it as a parameter to auth_url
