### ISSUE TITLE
PATCH request failure

### ISSUE THREAD

**Issue by hate5six** [vimeo/vimeo.py#57]
Are there any examples of a patch request in practice? I may have the incorrect syntax but when I try something like (for some video_id of mine): v.patch('https://api.vimeo.com/videos/video_id', {"data":{"privacy":{"view":"anybody"}}}) I get a 200 response but it doesn't actually change the privacy setting. Is this a bug or am I doing something wrong?

**Comment by Dashron** [comment]
Try dropping the data key, and just sending the request body directly

`{"privacy":{"view":"anybody"}}`

**Comment by hate5six** [comment]
Same issue. I get a 200 but the privacy doesn't change.

**Comment by greedo** [comment]
@hate5six the Vimeo library uses `requests` under the hood. So the correct way to send a requests with query parameters shown in this [example](http://docs.python-requests.org/en/latest/user/quickstart/#passing-parameters-in-urls) using our library would be:

```python
v.patch('/videos/{video_id}', data={"privacy":{"view":"anybody"}})
```
