### ISSUE TITLE
name 'basestring' is not defined :: python3

### ISSUE THREAD

**Issue by thornomad** [vimeo/vimeo.py#62]
Hi there - thanks for this!

There is an error in Python3 (works in Python2) triggered with `v.upload_picture`:

    File "/usr/local/lib/python3.4/site-packages/vimeo/upload.py", line 105, in upload_picture
        if isinstance(obj, basestring):
    NameError: name 'basestring' is not defined

I think this can be fixed fairly easily with a `try/except` statement upon import ... is it something you would be willing to fix?  I can create a pull request if that would help.

Could use this as a model: https://github.com/oxplot/fysom/issues/1

Damon

**Comment by Dashron** [comment]
Thanks for the info! Sending it off to one of our python devs.
