### ISSUE TITLE
AssertionError: Failed to create an upload ticket

### ISSUE THREAD

**Issue by nickedes** [vimeo/vimeo.py#64]
I have pyvimeo 0.3 as you can see here in `pip freeze`
```
$ pip freeze
Flask==0.10.1
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
pyimgur==0.5.2
pyodbc==3.0.10
PyVimeo==0.3.0
requests==2.7.0
six==1.9.0
Werkzeug==0.10.4
wheel==0.24.0
```
but when i tried to upload a video I got this error.
```
Traceback (most recent call last):
  File "client_secrets1.py", line 22, in <module>
    video_uri = v.upload('small.m4a')
  File "F:\Env\lib\site-packages\vimeo\upload.py", line 23, in upload
    return self._perform_upload(filename, ticket)
  File "F:\Env\lib\site-packages\vimeo\upload.py", line 38, in _perform_upload
    assert ticket.status_code == 201, "Failed to create an upload ticket"
AssertionError: Failed to create an upload ticket
```

**Comment by nickedes** [comment]
@greedo when will dis be solved ?

**Comment by greedo** [comment]
hi @nickedes could you tell me more information about your specific environment.
Python version, OS

Thanks

**Comment by nickedes** [comment]
@greedo `Python 2.7.10` and Windows 8

**Comment by greedo** [comment]
@nickedes 
I cannot replicate this error using your environment.

you should insert 
```python
"""Take an upload ticket and perform the actual upload."""

        print ticket.text
        assert ticket.status_code == 201, "Failed to create an upload ticket"
```
at https://github.com/vimeo/vimeo.py/blob/master/vimeo/upload.py#L41

Let me know what you get so I can debug further. You should also check you client `key`, `secret` and `token` and ensure they are correct.

**Comment by nickedes** [comment]
I did what you asked to:
```
{"error":"The app is not allowed to perform that action."}
Traceback (most recent call last):
  File "vimeo_upload_try.py", line 22, in <module>
    video_uri = v.upload('small.m4a')
  File "F:\Env\lib\site-packages\vimeo\upload.py", line 23, in upload
    return self._perform_upload(filename, ticket)
  File "F:\Env\lib\site-packages\vimeo\upload.py", line 38, in _perform_upload
    assert ticket.status_code == 201, "Failed to create an upload ticket"
AssertionError: Failed to create an upload ticket

```

It shows `app is not allowed to perform that action` :sob: 
You can see the code [here](https://gist.github.com/nickedes/7029827ff6ec690744b0)

The client `key`, `secret` and `token` are correct ,because I am able to print `about_me`. [See](https://gist.github.com/nickedes/7029827ff6ec690744b0#file-vimeo_upload_try-py-L12)

**Comment by greedo** [comment]
@nickedes 

You need to request upload access for your app. You can do this from your app's settings page.

**Comment by nickedes** [comment]
wait. what?
Can you explain @greedo

**Comment by Dashron** [comment]
There's more detailed steps at the top of our new upload documentation: https://developer.vimeo.com/api/upload/videos

**Comment by nickedes** [comment]
:+1:  Requested upload access!
Hopefully will get soon! :stuck_out_tongue_winking_eye: and then I will be back @greedo :speak_no_evil:
