### ISSUE TITLE
Crash when not specifying timeout

### ISSUE THREAD

**Issue by boazin** [vimeo/vimeo.py#65]
Not sure what was the intention of `kwargs['timeout'] = kwargs.get('timeout', (1, 30))`
(ln 66 client.py)

But if I don't specify timeout in the vimeo_obj.get(url)

I'm getting

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/vimeo/client.py", line 75, in caller
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 316, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 116, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 147, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was (1, 30), but it must be an int or float.
```

Maybe it worked with an older version of requests?

**Comment by sclm** [comment]
Yeah.  I think your hunch is right.  When it was written, you could provide a tuple for the connection and full request timeouts.  It seems that may have changed, but it requires a bit more investigation.

**Comment by greedo** [comment]
@boazin I am having trouble reproducing this error. Looking at the [Request docs](http://docs.python-requests.org/en/latest/user/advanced/#timeouts) it seems `timeout=(1, 30)` is still the way to specify this.Could you attach an gist of your code and we'll figure it out.

**Comment by boazin** [comment]
Well, I think it is a question of versions. Run `pip freeze` to see what you have. (mine is below)
The code is dead simple:
````
import vimeo
VIMEO_API_TOKEN = ""
VIMEO_API_SECRET = ""
TOKEN = ""
vimeo_username = ''
vimeo_obj = vimeo.VimeoClient(token=TOKEN, key=VIMEO_API_TOKEN, secret=VIMEO_API_SECRET)
vimeo_obj.get('/users?query={0}'.format(vimeo_username))
```

My `pip freeze`:
```
Pillow==2.3.0
PyVimeo==0.3.0
argparse==1.2.1
beautifulsoup4==4.3.2
boto==2.38.0
cffi==1.1.0
chardet==2.0.1
colorama==0.2.5
cryptography==0.9
enum34==1.0.4
google-api-python-client==1.4.0
html5lib==0.999
httplib2==0.9.1
idna==2.0
ipaddress==1.0.7
meld3==0.6.10
mercurial==2.8.2
oauth2==1.5.211
oauth2client==1.4.11
opengraph==0.5
pyOpenSSL==0.13
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.13
pymongo==3.0.2
python-dateutil==2.4.2
python-instagram==1.3.1
requests==2.2.1
rsa==3.1.4
sendgrid==1.4.0
simplejson==3.7.3
six==1.9.0
smtpapi==0.2.0
supervisor==3.0b2
uritemplate==0.6
urllib3==1.7.1
wheel==0.24.0
wsgiref==0.1.2
```

**Comment by greedo** [comment]
@boazin Unfortunately this error is coming deep from the bowels of `urllib3`. Requests changed in [version 2.4](https://github.com/kennethreitz/requests/blob/master/HISTORY.rst#240-2014-08-29) to support connect timeouts. If you upgrade your version of requests to at least 2.4.0 this issue will be fixed.

**Comment by boazin** [comment]
OK. Cool. That's weird because I'm using a docker image and building quite often (so it gets pip installed) I will look into the versions.
Thanks!
