### ISSUE TITLE
Can we upload using URL 

### ISSUE THREAD

**Issue by Geekathon** [vimeo/vimeo.py#68]
Can i just edit the upload function and change the "type: streaming" to "type:pull"  and do upload directly from URL ?

**Comment by Dashron** [comment]
Pull uploads are a single simple API call, and won't need the extra logic of the upload method. All HTTP methods are functions on your client (and map one to one with the [request](http://www.python-requests.org/en/latest/) library). So the following example should work:

```python
video_response = client.post('/me/videos', data={'type': 'pull', 'link':url});
```
