### ISSUE TITLE
Proper exceptions

### ISSUE THREAD

**Issue by Gwildor** [vimeo/vimeo.py#69]
It would be nice to have real exceptions I can catch, instead of asserts. For instance, when uploading a video, something like `UploadTicketCreationFailure` and `VideoCreationFailure` exceptions, with the information from the server. The server returns a proper error ("Your video file is not valid..." in mine case, because I was testing how it responds with non-video files), but those messages are not handled in any way.

**Comment by greedo** [comment]
@Gwildor would you mind pulling in the latest package from Github and letting me know if the new exceptions in #75 look good to you
