### ISSUE TITLE
Upload any file-like object

### ISSUE THREAD

**Issue by donaldharvey** [vimeo/vimeo.py#70]
It would be nice to be able to pass in a file object rather than a file name to the various upload functions, I'm having to generating temporary files for my use-case and it's pretty kludgy. 

Happy to write a patch if you think this would be useful!

**Comment by Dashron** [comment]
I definitely think it's useful, and your example is a great use case. Submit a PR, fill out our CLA: developer.vimeo.com/cla and I'll merge the code!
