### ISSUE TITLE
Video Replace Troubles since 12th November

### ISSUE THREAD

**Issue by oryxcam** [vimeo/vimeo.py#78]
Using PyVimeo to replace 8 videos automatically on a daily basis and worked fine for months.

Did not change anything, but it does not run anymore since 12th November 2015.

Suspect Vimeo having changed something.

Here the error I get:

Traceback (most recent call last):
  File "./vimeo_replacer.py", line 43, in <module>
    video_uri = v.upload('/home/daniel/MEGA_ORYX_TIMELAPSE_OUTPUT_FOLDER/1448723322/332_from_01-01-2015_to_27-11-2015_60s.mp4')
  File "/usr/local/lib/python2.7/dist-packages/vimeo/upload.py", line 28, in upload
    return self._perform_upload(filename, ticket)
  File "/usr/local/lib/python2.7/dist-packages/vimeo/upload.py", line 44, in _perform_upload
    raise VideoTicketCreationFailure(ticket, "Failed to create an upload ticket")
NameError: global name 'VideoTicketCreationFailure' is not defined

UPDATE 30.11.2015
Uploading goes fine; no "upload ticket" error

UPDATE 02.12.2015
Resolved, something needed to be fixed on Vimeo's side

**Comment by harrywykman** [comment]
I'm getting the same error described above:

Traceback (most recent call last):
  File "vimeo_api.py", line 42, in <module>
    video_uri = client.upload('/home/gerrard/code/python/timelapse/timelapse.mp4')
  File "/home/gerrard/.virtualenvs/timelapse/local/lib/python2.7/site-packages/vimeo/upload.py", line 28, in upload
    return self._perform_upload(filename, ticket)
  File "/home/gerrard/.virtualenvs/timelapse/local/lib/python2.7/site-packages/vimeo/upload.py", line 44, in _perform_upload
    raise VideoTicketCreationFailure(ticket, "Failed to create an upload ticket")
NameError: global name 'VideoTicketCreationFailure' is not defined

It is my first time trying to upload so it may be an issue on my end but hopefully not!

**Comment by Dashron** [comment]
Hey Everyone,

We're going to have a developer look into this soon. They may not be related issues, but we will update you when we have (or need!) more information!

**Comment by agilefox** [comment]
There was a problem where if the library did not get back a 201 when creating an upload ticket, it would try to throw an exception. However, this exception was undefined. 
I have corrected that and you will be able to `except` an `UploadTicketCreationFailure` which will give you further information on why the upload failed. 

I'll push a new package (3.3) shortly.
