### ISSUE TITLE
obvious error in upload_picture 

### ISSUE THREAD

**Issue by belonesox** [vimeo/vimeo.py#83]
Look
https://github.com/vimeo/vimeo.py/blob/master/vimeo/upload.py#L131

Exception if all OK

**Comment by Dashron** [comment]
Agreed, it looks pretty obvious. I'll get someone to look at it asap.

**Comment by Dashron** [comment]
If anyone encounters this issue before we resolve it, I bet you can just add an exclamation point to change it to not equal to 200.

`if obj.status_code !== 200:`

**Comment by inkadnb** [comment]
Any update on this?

**Comment by Dashron** [comment]
The temporary fix above should solve the problem. The actual release was delayed. I can not give a solid timeline at the moment.

**Comment by erunion** [comment]
Just pushed up a fix, and tagged [v0.3.4](https://github.com/vimeo/vimeo.py/tree/v0.3.4).

**Comment by sfelf** [comment]
Any chance this fix and version can be pushed to PyPi? We are currently running into problems due to this bug.

**Comment by erunion** [comment]
@sfelf Will get that updated this week.

**Comment by sfelf** [comment]
@erunion Thank you so much!

**Comment by erunion** [comment]
@sfelf Pushed `0.3.4` to PyPi.

**Comment by sfelf** [comment]
@erunion Thanks! We are installing now.
