### ISSUE TITLE
Handle limit exceeded API errors

### ISSUE THREAD

**Issue by williamroot** [vimeo/vimeo.py#86]
Starting August 9th, 2016 Vimeo began enforcing rate limits on all API apps. This enforcement includes API apps that were created prior to that date. Heavy users of the API were notified prior to this update with instructions for optimizing their API requests and potential impacts to their API implementations.

The API rate limit is generally based on a 15-minute rolling window (this window may change without notice). In other words, if you surpass the rate limit within a 15-minute time period your API app will be banned.

The actual rate limit varies depending on the app making the request, authentication as another user or the app owner, the endpoint being requested, usage of our JSON filter parameters in the request uri, and the rate limit tier of the app in our system.

Rate limit information is returned in the header of the response in the following format:

X-RateLimit-Limit →[total number of requests you're allowed to make]
X-RateLimit-Remaining →[number of requests remaining within time period]
X-RateLimit-Reset →[date/time the rate limit resets in UTC, formatted per ISO 8601: https://www.w3.org/TR/NOTE-datetime.]

Requests made after breaching the rate limit will return a 429 Too Many Requests error, with the date/time the ban will be lifted included in the header as the X-RateLimit-Reset value. Rate limit bans are enforced for roughly 60 minutes after the rate limit was initially breached (this duration may change without notice).

If your app continues to make a significant number of requests to the API after we return the 429 Too Many Requests error, the IP address making requests may be banned. We strongly recommend apps cease making requests to the API once a 429 error is returned. Requests banned according to the IP address will return the banned IP address in the X-Banned-IP header of the 429 error response.

**Comment by josesuarezcordova** [comment]
Hi, I'm basically new one using this API, and I getting constantly that issue

`Array ( [error] => Too many API requests. Wait an hour or so, then try again. `

I think that I doing well the authentication 

```
$lib = new Vimeo($client_id, $client_secret);
$lib->setToken($access_token);
$video_details = $lib->request('/videos/'.$video_id, ['per_page' => 2], 'GET'); 
```

but after few test, I get again the same error . message, but I cant find some practical example about how to avoid it. could you give me some clues please

thanks!
