### ISSUE TITLE
Vimeo.py Passing Integers as Header Values - No Longer Works with Requests 2.11.0

### ISSUE THREAD

**Issue by ShawonC** [vimeo/vimeo.py#88]
I'm currently using vimeo.py in a script to create a web page in our vimeo account page and post a video. The vimeo.py module uses the Requests library, but since the recent update of the requests library from version 2.10.0 to 2.11.0, I'm getting a header value error when trying to create the vimeo webpage. 
The actual error is: Header value 694886324 must be of type str or bytes, not <type 'int'>

When looking at the requests change log I see that in their miscellaneous fixes section it notes: "Some previous releases accidentally accepted non-strings as acceptable header values. This release does not." Here's a link to said change log: http://docs.python-requests.org/en/master/community/updates/#release-and-version-history

It looks like in the page creation somewhere in the vimeo.py module integers are getting passed as header values instead of strings or bytes. I took a cursory glance through some of the code but couldn't find the problem spot myself. I'd like to get this fixed so that we can keep using the most current version of Requests going forward.

**Comment by Calzzetta** [comment]
Hi @ShawonC ,

I did a small change that fix this issue, plese check: #89 

Regards,
Douglas

**Comment by ShawonC** [comment]
Hey @Calzzetta ,

Thanks for your response, sorry for the delay in my response. I updated the upload.py file as shown in your fix but am still getting the same header request value error. I'll dig into it myself this week and see if I can find any other issues. This may be a problem on my end at this point.

**Comment by Calzzetta** [comment]
Hi @ShawonC, please try to update your lib usinig pip.

**Comment by ShawonC** [comment]
That worked! 

Thanks Calzzetta for taking care of this.
