### ISSUE TITLE
APIRateLimitExceededFailure

### ISSUE THREAD

**Issue by jzelez** [vimeo/vimeo.py#93]
In `APIRateLimitExceededFailure` exception the code is calling super method but on non-existent `APIRateLimitExededFailure` class.

Also there is a call in `client.py` to `APIRateLimitExededFailure`. 

[Fix for this](https://github.com/EncircleInc/vimeo.py/commit/57ea766bca613ec92ca448dc9aa49fd7e46b7ba4)

**Comment by Sventour** [comment]
@jzelez it should be fixed in master. Haved you pulled from the master branch?

**Comment by jzelez** [comment]
No, I've just "pip installed" it normally. But I see now that it is fixed in master.
Sorry for bringing it up.
