### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by hamoid** [vimeo/vimeo.py#96]
There are no code examples for doing things like setting tags, categories, credits or collections. I can see endpoint documentation, but I wonder if it's possible accessing them using vimeo.py in its current state. Could you please post an example for calling POST or PUT methods? Thanks!

**Comment by Dashron** [comment]
Hey Hamoid,

We definitely need to add some examples, and flesh out the documentation, but for now try this.

Here's an example of how you would edit a video

https://developer.vimeo.com/api/endpoints/videos#PATCH/videos/{video_id}

```python
v = vimeo.VimeoClient(
    token=YOUR_ACCESS_TOKEN,
    key=YOUR_CLIENT_ID,
    secret=YOUR_CLIENT_SECRET)

response = v.patch("/videos/12345", data={"name": "New Name"});
```

Notice the urls and the data parameter. You can find all of the accepted params here: https://github.com/vimeo/vimeo.py/blob/master/vimeo/client.py#L64-L72

**Comment by hamoid** [comment]
I added the missing features I needed to this fork: https://github.com/hamoid/vimeo.py

**Comment by Dashron** [comment]
Looks good! We don't plan on adding functions for all the actions available in the API (It's very challenging to maintain) but a fork is always a good solution to fit your needs.
