### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by bongster** [vimeo/vimeo.py#98]
When i upload vimeo use Pyvimeo upload function at version 0.3.9

some times has a 502 bad gateway error.

so how is the problem??

vimeo side or api pyvimeo side?

**Comment by Dashron** [comment]
Is it consistent? It was likely a temporary outage, but if you are still having issues please reach out to us at vimeo.com/help/contact.

Additionally, for future reference you can check status.vimeo.com to see if we are experiencing any outages.

**Comment by bongster** [comment]
is this work status.vimeo.com site. 

i think that is weird.

because when i upload the vimeo use vimeo.py, raise a 502 bad gateway, but can not see status.vimeo.com site.

**Comment by bongster** [comment]
@Dashron could you help me.
