### ISSUE TITLE
Wrong info on passing URL parameters and setting API JSON filtering

### ISSUE THREAD

**Issue by etienned** [vimeo/vimeo.py#99]
In the README.md file it's written that to pass URL parameters, like for adding API JSON filtering, you need to set `data` but I think that should be `params` instead, as stated in the Requests' documentation.

**Comment by Dashron** [comment]
Thanks! I'll have a dev look into this and get back to you.

**Comment by erunion** [comment]
Nice catch!

**Comment by etienned** [comment]
You fixed the missing `add` also, great! I had forgotten to mention it.

Thanks
